package com.slt.slt;

import lombok.extern.slf4j.Slf4j;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@Slf4j
@MapperScan("com.slt.slt.mapper")
public class SltApplication {

    public static void main(String[] args) {

        SpringApplication.run(SltApplication.class, args);
        log.info("start已启动！");
    }

}


